spring:
  application:
    name: eurekaservidor
  security:
    basic:
      enabled: true
    user:
      name: eureka-user
      password: eaerever-surk

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
