spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/mscardcreditrealm

server:
  port: 8080

eureka:
  client:
    instance:
      prefer-ip-address: true
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-user:eaerever-surk@localhost:8761/eureka
